import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  zhinanSidebar: [
    {
      type: "category",
      label: "🚀 一、极速上手",
      // link: {type: 'doc', id: 'zhinan/index'}, // Assuming zhinan/index.md is the overview for this category
      items: [
        {
          type: "doc",
          label: "1️⃣ 初识来发信⏱3min",
          id: "zhinan/meet-laifaxin",
        },
        { type: "doc", label: "2️⃣ 注册与准备⏱3min", id: "zhinan/quick-start" },
        {
          type: "doc",
          label: "3️⃣ 搜索9999+客户⏱9min",
          id: "zhinan/newbie-10min-search-customers",
        },
        {
          type: "doc",
          label: "4️⃣ 背调1000+客户⏱3min",
          id: "zhinan/newbie-1min-background-check",
        },
        {
          type: "doc",
          label: "5️⃣ 保存1000+邮箱⏱3min",
          id: "zhinan/newbie-save-1000-emails",
        },
        {
          type: "doc",
          label: "6️⃣ 发一封追踪邮件⏱3min",
          id: "zhinan/newbie-first-trackable-email",
        },
        {
          type: "doc",
          label: "7️⃣ 群发营销100+邮件⏱5min",
          id: "zhinan/newbie-first-mass-sending-experience",
        },
        {
          type: "doc",
          label: "8️⃣ 导入验证999+邮箱⏱2min",
          id: "zhinan/newbie-import-verify-emails",
        },
        {
          type: "doc",
          label: "9️⃣ 免费福利 🎁 专属权益",
          id: "zhinan/rights-comparison",
        },
        {
          type: "doc",
          label: "🔟 最新活动 🎉 每日领取",
          id: "zhinan/event-summary",
        },
        { type: "doc", label: "🤔 常见问题 ❓ 问题反馈", id: "zhinan/faq" },
      ],
    },
    {
      type: "category",
      label: "🌟 二、特色功能",
      // link: {type: 'doc', id: 'zhinan/features/index'}, // Placeholder, adjust as needed
      items: [
        { type: "doc", label: "1️⃣ 客户搜索", id: "zhinan/customer-search" },
        { type: "doc", label: "2️⃣ 客户管理", id: "zhinan/customer-management" },
        { type: "doc", label: "3️⃣ 邮件营销", id: "zhinan/email-mass-sending" },
        { type: "doc", label: "4️⃣ 邮箱验证", id: "zhinan/email-verification" },
        { type: "doc", label: "5️⃣ 邮件追踪", id: "zhinan/email-tracking" },
      ],
    },
    {
      type: "category",
      label: "🔍 三、客户搜索",
      // link: {type: 'doc', id: 'zhinan/customer-search/index'}, // Placeholder, adjust as needed
      items: [
        {
          type: "doc",
          label: "1️⃣ 客户网站搜客",
          id: "zhinan/customer-website-search",
        },
        {
          type: "doc",
          label: "2️⃣ 精准买家搜索",
          id: "zhinan/precise-buyer-search",
        },
        {
          type: "doc",
          label: "3️⃣ 全球搜客引擎",
          id: "zhinan/global-search-engine",
        },
        {
          type: "doc",
          label: "4️⃣ 领英客户搜索",
          id: "zhinan/linkedin-customer-search",
        },
        {
          type: "doc",
          label: "5️⃣ 公司名称搜客",
          id: "zhinan/company-name-search",
        },
        {
          type: "doc",
          label: "6️⃣ 企业数据库",
          id: "zhinan/enterprise-database",
        }, // Adjusted from ./enterprise-database.md
        {
          type: "category",
          label: "7️⃣ 批量客户搜索",
          link: { type: "doc", id: "zhinan/bulk-search-task" },
          items: [
            {
              type: "doc",
              label: "① 高效搜索技巧",
              id: "zhinan/bulk-search-task",
            },
            {
              type: "category",
              label: "② 筛选搜索结果",
              link: { type: "doc", id: "zhinan/filter-search-results" },
              items: [
                {
                  type: "doc",
                  label: "⚙️ 筛选搜索结果",
                  id: "zhinan/filter-search-results",
                },
                {
                  type: "doc",
                  label: "🏷️ 常用筛选条件",
                  id: "zhinan/common-filter-conditions-for-search-customers",
                },
              ],
            },
            {
              type: "category",
              label: "③ 保存客户邮箱",
              link: { type: "doc", id: "zhinan/save-customer-emails" },
              items: [
                {
                  type: "doc",
                  label: "📧 保存客户邮箱",
                  id: "zhinan/save-customer-emails",
                },
                {
                  type: "doc",
                  label: "⚖️ 邮箱类型对比",
                  id: "zhinan/comparison-of-three-types-of-mailboxes",
                },
                {
                  type: "doc",
                  label: "💰 助你降本增效",
                  id: "zhinan/control-quantity-cost-reduction-and-efficiency-enhancement",
                },
              ],
            },
            {
              type: "doc",
              label: "④ 搜客保存记录",
              id: "zhinan/search-save-records",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "📇 四、客户管理",
      link: { type: "doc", id: "zhinan/manage-contacts" },
      items: [
        {
          type: "category",
          label: "👤 联系人",
          link: { type: "doc", id: "zhinan/manage-contacts" },
          items: [
            { type: "doc", label: "➕ 添加联系人", id: "zhinan/add-contacts" },
            {
              type: "doc",
              label: "📋 管理联系人",
              id: "zhinan/manage-contacts",
            },
            {
              type: "doc",
              label: "🏷️ 标签与视图",
              id: "zhinan/contacts-tags-views",
            },
            {
              type: "doc",
              label: "📤 导出联系人",
              id: "zhinan/export-contacts",
            },
          ],
        },
        {
          type: "category",
          label: "🏢 公司",
          link: { type: "doc", id: "zhinan/manage-company" },
          items: [
            { type: "doc", label: "➕ 添加公司", id: "zhinan/add-company" },
            { type: "doc", label: "📋 管理公司", id: "zhinan/manage-company" },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "📈 五、邮件营销",
      link: { type: "doc", id: "zhinan/email-mass-sending" },
      items: [
        { type: "doc", label: "🚀 邮件群发", id: "zhinan/email-mass-sending" },
        { type: "doc", label: "📊 追踪记录", id: "zhinan/tracking-logs" },
      ],
    },
    {
      type: "category",
      label: "📨 六、邮件管理",
      link: { type: "doc", id: "zhinan/email-list" },
      items: [
        {
          type: "category",
          label: "✍️ 撰写邮件",
          link: { type: "doc", id: "zhinan/compose-new-email" },
          items: [
            {
              type: "doc",
              label: "💡 写新邮件",
              id: "zhinan/compose-new-email",
            },
            { type: "doc", label: "🎨 邮件编辑", id: "zhinan/email-editing" },
          ],
        },
        {
          type: "category",
          label: "🗂️ 管理邮件",
          link: { type: "doc", id: "zhinan/check-new-emails" },
          items: [
            {
              type: "doc",
              label: "📬 收新邮件",
              id: "zhinan/check-new-emails",
            },
            { type: "doc", label: "📜 邮件列表", id: "zhinan/email-list" },
            {
              type: "doc",
              label: "🗄️ 智能分类",
              id: "zhinan/email-categorization",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "🛠️ 七、其他功能",
      link: { type: "doc", id: "zhinan/tag-management" },
      items: [
        { type: "doc", label: "🏷️ 标签管理", id: "zhinan/tag-management" },
        { type: "doc", label: "📄 客户字段", id: "zhinan/customer-fields" },
        { type: "doc", label: "📝 邮件模板", id: "zhinan/email-templates" },
        { type: "doc", label: "✒️ 邮件签名", id: "zhinan/email-signature" },
        {
          type: "doc",
          label: "📎 附件管理",
          id: "zhinan/attachment-management",
        },
        {
          type: "doc",
          label: "🚫 黑名单管理",
          id: "zhinan/blacklist-management",
        },
        { type: "doc", label: "⚙️ 系统账号", id: "zhinan/system-account" },
        { type: "doc", label: "📧 邮箱账号", id: "zhinan/email-account" },
      ],
    },
    {
      type: "category",
      label: "🏢 八、企业版",
      link: { type: "doc", id: "zhinan/business-management" },
      items: [
        {
          type: "category",
          label: "🔐 企业权限控制",
          link: { type: "doc", id: "zhinan/business-management" },
          items: [
            {
              type: "doc",
              label: "🏢 企业基础信息",
              id: "zhinan/business-management",
            },
            {
              type: "doc",
              label: "👥 部门架构管理",
              id: "zhinan/department-management",
            },
            {
              type: "doc",
              label: "👨‍💼 团队成员管理",
              id: "zhinan/member-management",
            },
            {
              type: "doc",
              label: "🔑 权限控制管理",
              id: "zhinan/permissions-management",
            },
            {
              type: "doc",
              label: "🔄 数据分享同步",
              id: "zhinan/sync-management",
            },
            {
              type: "doc",
              label: "📊 额度管理配置",
              id: "zhinan/quota-management",
            },
          ],
        },
        {
          type: "category",
          label: "✨ 企业专属功能",
          link: { type: "doc", id: "zhinan/search-privileges" },
          items: [
            {
              type: "doc",
              label: "👑 尊享搜客特权",
              id: "zhinan/search-privileges",
            },
            {
              type: "doc",
              label: "💬 WhatsApp搜索",
              id: "zhinan/whatsapp-search",
            },
            {
              type: "doc",
              label: "🤝 客户归属管理",
              id: "zhinan/ownership-management",
            },
          ],
        },
      ],
    },
  ],
  youxiangSidebar: [
    {
      type: "category",
      label: "个人邮箱",
      // link: {type: 'doc', id: 'youxiang/index'}, // Assuming youxiang/index.md is the overview
      items: [
        {
          type: "doc",
          label: "常用个人邮箱",
          id: "youxiang/100-gerenyouxiang-personal-mailbox",
        },
        {
          type: "doc",
          label: "谷歌邮箱（@gmail.com）",
          id: "youxiang/101-guge-gmailyouxiang-google-personal-email",
        },
        {
          type: "doc",
          label: "雅虎邮箱（@yahoo.com）",
          id: "youxiang/102-yahu-yahooyouxiang-yahoo-personal-mailbox",
        },
        {
          type: "doc",
          label: "阿里邮箱（@aliyun.com）",
          id: "youxiang/103-ali-aliyunyouxiang-ali-personal-email",
        },
        {
          type: "doc",
          label: "电信邮箱（@189.cn）",
          id: "youxiang/104-dianxin-189youxiang-telecom-personal-mailbox",
        },
        {
          type: "doc",
          label: "搜狐邮箱（@sohu.com）",
          id: "youxiang/105-souhu-sohuyouxiang-sohu-personal-email",
        },
        {
          type: "doc",
          label: "腾讯邮箱（@qq/@foxmail）",
          id: "youxiang/106-tengxun-qqyouxiang-tencent-personal-email",
        },
        {
          type: "doc",
          label: "网易邮箱（163/126/yeah/188）",
          id: "youxiang/107-wangyi-163youxiang-netease-personal-email",
        },
        {
          type: "doc",
          label: "微软邮箱（outlook/hotmail）",
          id: "youxiang/108-weiruan-outlookyouxiang-microsoft-personal-email",
        },
        {
          type: "doc",
          label: "新浪邮箱（sina.com/sina.cn）",
          id: "youxiang/109-xinlang-sinayouxiang-sina-personal-email",
        },
        {
          type: "doc",
          label: "移动邮箱（@139.com）",
          id: "youxiang/110-yidong-139youxiang-china-mobile-personal-email",
        },
        {
          type: "doc",
          label: "电信邮箱（@21cn.com）",
          id: "youxiang/111-dianxin-21cnyouxiang-telecom-personal-mailbox",
        },
        {
          type: "doc",
          label: "完美邮箱（@88/@111/email）",
          id: "youxiang/112-wanmei-88youxiang-perfect-personal-mailbox",
        },
        {
          type: "doc",
          label: "苹果邮箱（@icloud.com）",
          id: "youxiang/113-pingguo-icloudyouxiang-apple-personal-email",
        },
        {
          type: "doc",
          label: "AOL邮箱（@aol.com）",
          id: "youxiang/114-aol-aolyouxiang-aol-personal-email",
        },
        {
          type: "doc",
          label: "Yandex邮箱（@yandex.com）",
          id: "youxiang/115-yandex-yandexyouxiang-yandex-personal-email",
        },
        {
          type: "doc",
          label: "mail.ru邮箱(@mail.ru)",
          id: "youxiang/116-mailru-mailyouxiang-mail-personal-email",
        },
      ],
    },
    {
      type: "category",
      label: "企业邮箱",
      // link: {type: 'doc', id: 'youxiang/enterprise/index'}, // Placeholder, adjust as needed
      items: [
        {
          type: "doc",
          label: "常用企业邮箱",
          id: "youxiang/200-qiyeyouxiang-enterprise-mailbox",
        },
        {
          type: "doc",
          label: "谷歌企业邮箱",
          id: "youxiang/201-guge-qiyeyouxiang-google-business-mail",
        },
        {
          type: "doc",
          label: "263企业邮箱",
          id: "youxiang/202-263-qiyeyouxiang-263-business-mail",
        },
        {
          type: "doc",
          label: "阿里云企业邮箱",
          id: "youxiang/203-aliyun-qiyeyouxiang-alibaba-cloud-enterprise-mailbox",
        },
        {
          type: "doc",
          label: "网易企业邮箱",
          id: "youxiang/204-wangyi-qiyeyouxiang-netease-enterprise-mailbox",
        },
        {
          type: "doc",
          label: "腾讯企业邮箱",
          id: "youxiang/205-tengxun-qiyeyouxiang-tencent-enterprise-mailbox",
        },
        {
          type: "doc",
          label: "35企业邮箱",
          id: "youxiang/206-35-qiyeyouxiang-35-enterprise-mailbox",
        },
        {
          type: "doc",
          label: "ZOHO企业邮箱",
          id: "youxiang/207-zoho-qiyeyouxiang-zoho-enterprise-mailbox",
        },
      ],
    },
  ],
  shareSidebar: [
    {
      type: "category",
      label: "邮箱",
      items: [
        {
          type: "category",
          label: "免费篇",
          collapsed: true,
          link: {
            type: "doc",
            id: "share/mailbox/apply-for-free-email",
          },
          items: [
            {
              type: "doc",
              label: "申请免费邮箱",
              id: "share/mailbox/apply-for-free-email",
            },
            {
              type: "category",
              label: "免费企业邮箱",
              collapsed: true,
              items: [
                {
                  type: "doc",
                  label: "lark企业邮箱",
                  id: "share/mailbox/free-enterprise-email-larksuite",
                },
                {
                  type: "doc",
                  label: "飞书企业邮箱",
                  id: "share/mailbox/free-enterprise-email-larksuite",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "邮件",
      items: [
        {
          type: "category",
          label: "逼单篇",
          collapsed: true,
          link: {
            type: "doc",
            id: "share/email/national-day-holiday-push-orders-foreign-trade-peoples-emergency-action-guide",
          },
          items: [
            {
              type: "doc",
              label: "国庆逼单",
              id: "share/email/national-day-holiday-push-orders-foreign-trade-peoples-emergency-action-guide",
            },
          ],
        },
        {
          type: "category",
          label: "开发篇",
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "腾讯元宝打造cold email",
              id: "share/email/Create-High-Response-Foreign-Trade-Development-Letters-with-Tencent-Yuanbao",
            },
          ],
        },
        {
          type: "category",
          label: "跟进篇",
          collapsed: true,
          items: [
            {
              type: "link",
              label: "更新中",
              href: "#",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "教程",
      items: [
        {
          type: "category",
          label: "建站篇",
          collapsed: true,
          items: [
            {
              type: "doc",
              label: "10分钟打造精美落地页",
              id: "share/website/ai-powered-website-in-10-minutes",
            },
            {
              type: "doc",
              label: "图床批量转移指南-小书匠",
              id: "share/website/story-writer-github-image-hosting-guide",
            },
            {
              type: "doc",
              label: "Bolt Token不够用？带你薅！",
              id: "share/website/bolt-token-referral-guide",
            },
          ],
        },
      ],
    },
  ],
  khkfSidebar: [
    {
      type: "category",
      label: "客户开发",
      link: { type: "doc", id: "zhinan/search-logic-section" },
      items: [
        {
          type: "doc",
          label: "1️⃣搜客逻辑篇",
          id: "zhinan/search-logic-section",
        },
        {
          type: "doc",
          label: "2️⃣客户画像篇",
          id: "zhinan/customer-profiling-section",
        },
        {
          type: "category",
          label: "3️⃣基础语法篇",
          link: { type: "doc", id: "zhinan/basic-grammar-section" },
          items: [
            {
              type: "doc",
              label: "🔍谷歌基础语法",
              id: "zhinan/basic-grammar-section",
            },
            {
              type: "doc",
              label: "🌟社媒搜客语法",
              id: "zhinan/social-media-recruiter-syntax",
            },
            {
              type: "doc",
              label: "🌟B2B搜客语法",
              id: "zhinan/b2b-recruiter-syntax",
            },
            {
              type: "doc",
              label: "🌟海关数据语法",
              id: "zhinan/customs-data-syntax",
            },
          ],
        },
        {
          type: "doc",
          label: "4️⃣种子客户篇",
          id: "zhinan/seed-customer-section",
        },
        {
          type: "doc",
          label: "5️⃣特征分析篇",
          id: "zhinan/feature-analysis-section",
        },
        {
          type: "doc",
          label: "6️⃣搜索实战篇",
          id: "zhinan/search-practice-section",
        },
        {
          type: "category",
          label: "7️⃣高效筛选篇",
          link: { type: "doc", id: "zhinan/efficient-filtering-section" },
          items: [
            {
              type: "doc",
              label: "🔍高效筛选",
              id: "zhinan/efficient-filtering-section",
            },
            {
              type: "doc",
              label: "🌟常用筛选",
              id: "zhinan/common-filter-conditions-for-search-customers",
            },
          ],
        },
        {
          type: "doc",
          label: "8️⃣客户管理篇",
          id: "zhinan/customer-management-section",
        },
        {
          type: "doc",
          label: "9️⃣邮件内容篇",
          id: "zhinan/email-content-section",
        },
        {
          type: "doc",
          label: "🔟效率工具篇",
          id: "zhinan/efficiency-tools-section",
        },
      ],
    },
  ],
  chajianSidebar: [
    {
      type: "category",
      label: "谷歌地图",
      // link: {type: 'doc', id: 'chajian/index'}, // Assuming chajian/index.md is the overview
      items: [
        {
          type: "doc",
          label: "产品介绍",
          id: "chajian/what-is-google-maps-business-collection",
        },
        {
          type: "doc",
          label: "下载安装",
          id: "chajian/how-to-install-google-maps-plugin",
        },
        {
          type: "category",
          label: "使用说明",
          link: { type: "doc", id: "chajian/how-to-use-google-maps-plugin" },
          items: [
            {
              type: "doc",
              label: "如何使用谷歌地图插件？",
              id: "chajian/how-to-use-google-maps-plugin",
            },
            {
              type: "doc",
              label: "如何使用谷歌地图开发客户？",
              id: "chajian/how-to-use-google-maps-for-customer-development",
            },
            {
              type: "doc",
              label: "云端数据同步与管理地图商家",
              id: "chajian/cloud-synchronize-merchants-and-centralized-data-management",
            },
            {
              type: "doc",
              label: "快速筛选目标商家列表",
              id: "chajian/how-to-quickly-filter-target-google-maps-businesses",
            },
            {
              type: "doc",
              label: "如何从地图中提取邮箱？",
              id: "chajian/how-to-extract-email-from-google-maps",
            },
            {
              type: "doc",
              label: "如何从地图中提取电话？",
              id: "chajian/how-to-extract-phone-number-from-google-maps",
            },
            {
              type: "doc",
              label: "如何从地图中提取地址？",
              id: "chajian/how-to-extract-detailed-address-from-google-maps",
            },
            {
              type: "doc",
              label: "如何提取商家经度和纬度？",
              id: "chajian/how-to-extract-longitude-and-latitude-from-google-maps",
            },
            {
              type: "doc",
              label: "如何提取纽约的餐厅列表？",
              id: "chajian/how-to-extract-restaurant-list-in-new-york-area-from-google-maps",
            },
            {
              type: "doc",
              label: "如何多开谷歌地图插件？",
              id: "chajian/how-to-multi-open-google-maps-plugin",
            },
            {
              type: "doc",
              label: "提升城市较多地区采集效率",
              id: "chajian/improve-google-maps-data-collection-efficiency-focus-on-popular-cities",
            },
          ],
        },
        {
          type: "category",
          label: "常见问题",
          link: { type: "doc", id: "chajian/google-maps-plugin-faq" },
          items: [
            {
              type: "doc",
              label: "谷歌地图插件常见问题",
              id: "chajian/google-maps-plugin-faq",
            },
            {
              type: "doc",
              label: "如何修改谷歌地图界面语言？",
              id: "chajian/how-to-display-google-maps-interface-language-as-english",
            },
          ],
        },
        {
          type: "doc",
          label: "邀请福利",
          id: "chajian/what-are-the-benefits-of-inviting-friends-to-use-the-google-maps-plugin",
        },
      ],
    },
  ],
};

export default sidebars;
